
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpsnwizithzxhsufultp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwc253aXppdGh6eGhzdWZ1bHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjE2OTYsImV4cCI6MjA1OTUzNzY5Nn0.F38NqtB74iJqqEVoD_PphWDaltKU2dzGuYCLa6R_hYk";

// Configuração de opções para melhor tratamento de imagens
const supabaseOptions = {
  auth: {
    persistSession: true,
  },
  global: {
    fetch: (url: string, options: RequestInit) => {
      // Aumentar timeout para processamento de imagens
      const customFetch = fetch(url, options);
      return Promise.race([
        customFetch,
        new Promise<Response>((_, reject) => 
          setTimeout(() => reject(new Error('Timeout')), 120000) // 2 minutos de timeout
        ) as Promise<Response>,
      ]);
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);
